tap 'appsketch/dafont'
tap 'argon/mas'
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/command-not-found'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/services'
tap 'mpv-player/mpv'
brew 'autoconf'
brew 'automake'
brew 'libpng'
brew 'freetype'
brew 'pkg-config'
brew 'fontconfig'
brew 'gettext'
brew 'libffi'
brew 'pcre'
brew 'glib'
brew 'pixman'
brew 'cairo'
brew 'coreutils'
brew 'makedepend'
brew 'openssl'
brew 'curl', args: ['with-openssl']
brew 'node'
brew 'diff-so-fancy'
brew 'lame'
brew 'fribidi'
brew 'git'
brew 'gobject-introspection'
brew 'icu4c'
brew 'harfbuzz'
brew 'yasm'
brew 'libass'
brew 'jpeg'
brew 'xz'
brew 'libtiff'
brew 'leptonica'
brew 'tesseract'
brew 'x264'
brew 'xvid'
brew 'libtool'
brew 'zimg'
brew 'ffmpeg'
brew 'gdbm'
brew 'libarchive'
brew 'little-cms2'
brew 'lua'
brew 'readline'
brew 'sqlite'
brew 'python3'
brew 'vapoursynth'
brew 'youtube-dl'
brew 'mpv', args: ['with-bundle', 'with-libarchive', 'with-vapoursynth']
brew 'nvm'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'
brew 'argon/mas/mas'
brew 'homebrew/dupes/grep', args: ['with-default-names']
cask 'appcleaner'
cask 'atom'
cask 'cheatsheet'
cask 'coconutbattery'
cask 'dropbox'
cask 'epubquicklook'
cask 'etrecheck'
cask 'flash-npapi'
cask 'flux'
cask 'font-fira-code'
cask 'font-fira-sans'
cask 'font-inconsolata'
cask 'font-open-sans'
cask 'font-raleway'
cask 'font-roboto'
cask 'font-source-sans-pro'
cask 'google-chrome-canary'
cask 'ifilex'
cask 'imageoptim'
cask 'keepingyouawake'
cask 'monolingual'
cask 'onyx'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'qlvideo'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'quicknfo'
cask 'rdm'
cask 'silverlight'
cask 'sketch'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'supaview'
cask 'the-unarchiver'
cask 'transmission'
cask 'transmit'
cask 'webpquicklook'
cask 'yemuzip'
cask 'ynab'
mas 'Chatty (2.0.2)', id: 981117463
mas 'Numbers (4.0.5)', id: 409203825
mas '1Password (6.3.5)', id: 443987910
mas 'Paste (2.0.1)', id: 967805235
mas 'ReadKit (2.4.3)', id: 588726889
mas 'Pages (6.0.5)', id: 409201541
mas 'Keynote (7.0.5)', id: 409183694
mas 'Tweetbot (2.4.4)', id: 557168941
