tap 'argon/mas'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/command-not-found'
tap 'homebrew/core'
brew 'icu4c'
brew 'boost'
brew 'xz'
brew 'pkg-config'
brew 'libpng'
brew 'freetype'
brew 'fontconfig'
brew 'pixman'
brew 'gettext'
brew 'libffi'
brew 'glib'
brew 'cairo'
brew 'texi2html'
brew 'yasm'
brew 'pcre'
brew 'git'
brew 'x264'
brew 'lame'
brew 'xvid'
brew 'fribidi'
brew 'gobject-introspection'
brew 'harfbuzz'
brew 'libass'
brew 'makedepend'
brew 'openssl'
brew 'ffmpeg'
brew 'gdbm'
brew 'lua'
brew 'highlight'
brew 'jpeg'
brew 'libtiff'
brew 'little-cms2'
brew 'youtube-dl'
brew 'readline'
brew 'sqlite'
brew 'python3'
brew 'mpv', args: ['with-bundle']
brew 'ocaml'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'
brew 'argon/mas/mas'
cask 'atom'
cask 'caprine'
cask 'cheatsheet'
cask 'dropbox'
cask 'etrecheck'
cask 'flash'
cask 'flux'
cask 'google-chrome-canary'
cask 'imagealpha'
cask 'imageoptim'
cask 'keepingyouawake'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'qlvideo'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'silverlight'
cask 'sketch'
cask 'sketch-toolbox'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'svgcleaner'
cask 'the-unarchiver'
cask 'transmission'
cask 'transmit'
cask 'uninstallpkg'
cask 'yemuzip'
cask 'ynab'
mas 'Tweetbot', id: 557168941
mas '1Password', id: 443987910
mas 'Paste', id: 967805235
mas 'ReadKit', id: 588726889
mas 'Pages', id: 409201541
mas 'Keynote', id: 409183694
mas 'Numbers', id: 409203825
