require("nvim-treesitter.configs").setup({
	sync_install = false,
	highlight = { enable = true, additional_vim_regex_highlighting = { "markdown" } },
	indent = { enable = true },
	auto_install = true,
	ensure_installed = {
		"bash",
		"c_sharp",
		"diff",
		"html",
		"javascript",
		"lua",
		"luadoc",
		"markdown",
		"markdown_inline",
		"typescript",
		"vim",
		"vimdoc",
		"yaml",
	},
})
